language: java

os: linux
dist: bionic
jdk: openjdk11

before_install:
  - chmod +x gradlew

install: gradle wrapper --gradle-version 5.2

before_script:
  - "Xvfb :99 &"
  - "export DISPLAY=:99"

script:
  - "./gradlew build"

maven_build:
  stage: build
  script:
    - "mvn clean package -Djava.awt.headless=true"